spring:
  datasource:
    url: ENC(SAKSQn3SnqBUaP0a/b5gO0XZ5NNIWT4SqaphgnDtV+Nukoggg+CTg8k/2HqmNcU6eEFKfvKEOMX56t6MIr1AEdnDrYyntYNhVIydyjvvzKQFBgtvA8Nk0Dgt0JHY3YVN6toOo3xTRv0+pSzr/+ME6lPKrO3LZGaya9q91fOP8v7ORBBj3UJU9wZpTzOdbOM3A7WzbCKhYCY=)
    username: ENC(lm5qVbzDpMrKtVUznFBQcw==)
    password: ENC(WEJRws5bvxWIqxodlpqsjwSQctB4C5Kg)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: mysql
    properties:
      hibernate:
        format_sql: true