jasypt:
  encryptor:
    password: hcjweg3120
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: threedaysapitokensecretkey123149398230
cloud:
  aws:
    s3:
      bucket: itsubucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIARREOKLWWNCOBGJHR
      secretKey: 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
server:
  port: 5000