#spring:
#  datasource:
#    url: jdbc:mysql://threedays.cnaor4agdclw.ap-northeast-2.rds.amazonaws.com :3306/threedays
#    username: root
#    password: threedays
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database: mysql
#    properties:
#      hibernate:
#        format_sql: true
##  profiles:
##    active: test
#jwt:
#  secret: threedaysapitokensecretkey123149398230